### ISSUE TITLE
[BUG]: Can't build strapi admin panel anymore

### ISSUE THREAD

**Issue by bitmonti** [Fekide/strapi-plugin-translate#378] opened 2023-11-13 08:57 UTC
**Describe the bug**
Opened issue [#18711](https://github.com/strapi/strapi/issues/18711)

**To Reproduce**

Git repository: [link](https://github.com/bitmonti/support-strapi-build-broken.git)
1. npm install
2. npm run build

Stackblitz: [link](https://stackblitz.com/~/github.com/bitmonti/support-strapi-build-broken)
1. npm rebuild
2. npm run build

**System:**

Ubuntu 22.04.3 LTS
node: **v**18.17.1
npm: **v**9.6.7

**Plugin config**
Please add your plugin config here, e.g.

```js
module.exports = {
    translate: {
      enabled: true,
      config: {
        provider: "deepl",
        providerOptions: {
          apiKey: env("DEEPL_API_PROFESSIONAL"),
          apiUrl: env("DEEPL_API_URL"),
        },
      },
    },
}
```

**Comment by marioguima** [comment] 2023-11-13 19:40
I got the same error.
If I uninstall the plugin the admin compiles correctly
How the @bitmonti commented on issues [#18711](https://github.com/strapi/strapi/issues/18711)

**Comment by esiao** [comment] 2023-11-15 18:13
The issue is likely on this import
https://github.com/Fekide/strapi-plugin-translate/blob/60b42c5404203bfad610ba559780c71d0a6421dc/plugin/admin/src/components/CMEditViewTranslateLocale/index.js#L51

**Comment by layaxx** [comment] 2023-11-16 18:11
Hey guys, 
thanks for raising this Issue and for providing a reproduction repo.
I think @esiao is correct, although this is not the only import from the i18n plugin package causing this problem.
The problem is not even that those files are missing, they are just not marked as being exported in the package.json file.
I will look into possible solutions, but can unfortunately not give you any timeframe right now.

**Closed** 2023-11-19 10:23 UTC
Labels: investigate
