### ISSUE TITLE
[BUG]: Showing error after translate from default language

### ISSUE THREAD

**Issue by raghav-zwt** [Fekide/strapi-plugin-translate#231] opened 2023-06-06 13:22 UTC
**Describe the bug**
When clicking on "Yes, fill in" after showing an error like "Woops! Something went wrong. Please, try again."

**To Reproduce**
1. Go to the edit page and click on 'Translate from another locale'
2. Click on "Yes, fill in" https://prnt.sc/CZI9rf4tC5I-
3. After Seeing an error like "Woops! Something went wrong. Please, try again."

**Expected behavior**
It should filled inputs in selected language 

**Screenshots**
- https://prnt.sc/CZI9rf4tC5I-
- https://prnt.sc/uk5hNCvCv7J3

**System (please complete the following information):**
 - OS: MAC
 - Browser chrome
 - Versions:
   - strapi: 4.9.0
   - strapi-plugin-translate: 1.1.5
   - provider: trapi-provider-translate-deepl@1.1.5

**Plugin config**
Please add your plugin config here, e.g.
```js
module.exports = {
  translate: {
    enabled: true,
    config: {
      provider: 'deepl',
      providerOptions: {
        apiKey: '*************'
      },
      translatedFieldTypes: [
        'string',
        { type: 'text', format: 'plain' },
        { type: 'richtext', format: 'markdown' },
        'component',
        'dynamiczone',
      ],
      translateRelations: true,
    },
  },
}
```

**Comment by layaxx** [comment] 2023-06-10 22:00
Hi @Imran-cse,
- are you using other plugins besides `strapi-plugin-translate`?
- what (type of) fields does the entity you are trying to translate consist of?

**Comment by Imran-cse** [comment] 2023-06-11 16:21
@layaxx Yes I'm using other plugins but for translating only using this one.

Entity consists of all the types of entity the plugin supports as markdown, dynamiczone, string, components.

**Comment by Shekhar-Zealous** [comment] 2023-06-14 09:17
@layaxx Error is generated when click on save for the different locale data after the data is translated. Check the below error image: 
![image](https://github.com/Fekide/strapi-plugin-translate/assets/104756792/6bb0bcfd-9431-4b82-9bf5-9b065094658e)

**Comment by layaxx** [comment] 2023-06-14 18:49
Hi ,
I have so far not been able to reproduce this problem.
Again, could you please list your others plugins, even if they are not directly related to translation? From the screenshots it looks like you are using a non-default editor for your richtext fields.
Apart from that, would any one of you be able to share a minimal reproduction example?

**Comment by Shekhar-Zealous** [comment] 2023-06-16 05:26
> Hi @raghav-zwt @Imran-cse @Shekhar-Zealous, I have so far not been able to reproduce this problem. Again, could you please list your others plugins, even if they are not directly related to translation? From the screenshots it looks like you are using a non-default editor for your richtext fields. Apart from that, would any one of you be able to share a minimal reproduction example?

I am using CKEditor 5 plugin for text editor. As far as I know, the editor is not creating any problems :/
There is something wrong with the plugin.

**Comment by layaxx** [comment] 2023-06-17 21:13
Ok, i still cannot reproduce this, so CKEditor might in fact not be related to this. There might very well be something wrong with this plugin, but I cannot work on fixing it unless I can reproduce this error.

@Shekhar-Zealous  Could you share the schema.json files of the content-types you encountered this issue with? Same actually also goes for your other issue (#232)

**Comment by Shekhar-Zealous** [comment] 2023-07-24 09:27
@layaxx @sargreal You can close this bug as it was fixed with this issue https://github.com/Fekide/strapi-plugin-translate/issues/246

**Closed** 2023-07-24 09:28 UTC
Labels: investigate
