### ISSUE TITLE
Content not being translated

### ISSUE THREAD

**Issue by anatolykopyl** [Fekide/strapi-plugin-translate#66] opened 2023-01-20 17:54 UTC
## Steps to reproduce:
1. Open a document with English locale filled in
2. Switch to French
3. Press "Translate from another locale"
4. Select English

## Expected result:
Fields get translated

## Actual result:
Fields get filled with English as if the native "Fill in from another locale" has been pressed.
The admin dashboard sends a POST request to `/translate/translate` with the following payload:
```json
{
  "id":1,
  "sourceLocale":"en",
  "targetLocale":"fr",
  "contentTypeUid":"api::about.about"
}
```

and gets this `200` response:
```json
{
  "name": "The name of the document",
  "createdAt": "2023-01-04T08:49:43.842Z",
  "updatedAt": "2023-01-20T17:41:35.467Z",
  "locale": "en",
  "body": "Some text in english, not translated",
  "another_field": "Not translated also"
  "createdBy": {
    "id": 1
  },
  "updatedBy": {
    "id": 1
  },
  "localizations": [
    {
      "id": 2
    },
    {
      "id": 1
    }
  ]
}
```

## Plugin config:
```ts
// plugins.ts
export default ({ env }) => ({
  translate: {
    enabled: true,
    config: {
      provider: 'deepl',
      providerOptions: {
        apiKey: 'xxx'
      },
    },
  },
})
```

## Versions:
```json
"@strapi/strapi": "4.5.5",
"strapi-plugin-translate": "1.0.0",
"strapi-provider-translate-deepl": "1.0.0",
```

**Comment by JonasGruenwald** [comment] 2023-01-21 00:49
I have the same issue, can reproduce by just trying to translate the string 'translation' from German (Übersetzung) to English, it just returns the original German string.

Payload

```
{
  "id": 5,
  "sourceLocale": "de",
  "targetLocale": "en",
  "contentTypeUid": "api::landing-slide.landing-slide"
}
```

Response

```
{
  "Title": "Übersetzung",
  "Content": null,
  "createdAt": "2023-01-21T00:43:26.130Z",
  "updatedAt": "2023-01-21T00:43:40.105Z",
  "publishedAt": "2023-01-21T00:43:40.098Z",
  "locale": "de",
  "ExhibitionImage": null,
  "ExhibitionFeature": null,
  "createdBy": {
    "id": 1
  },
  "updatedBy": {
    "id": 1
  },
  "localizations": [
    {
      "id": 5
    }
  ]
}
```

**Comment by sargreal** [comment] 2023-01-21 10:13
The only explanation I have right now is that the `deepl` provider is not properly selected in the config 🤔 

Can you share your translate plugin configuration?

**Comment by JonasGruenwald** [comment] 2023-01-21 11:48
For me it's this:
```
translate: {
    enabled: true,
    config: {
      // Choose one of the available providers
      provider: 'deepl',
      // Pass credentials and other options to the provider
      providerOptions: {
        // your API key - required and wil cause errors if not provided
        apiKey: env('DEEPL_API_KEY'),
      },
      translatedFieldTypes: [
        'string',
        { type: 'text', format: 'plain' },
        { type: 'richtext', format: 'markdown' },
        'component',
        'dynamiczone',
      ],
    },
  }
```

But I have also tried without the translated field types option, similar to the person who posted the issue.

I noticed however that when I supply an invalid API key, there is no error during translation, which is strange.
On the other hand, if I change the provider value from 'deepl' to something else, I do get an error during startup, so it does seem like it is selected properly?

**Comment by layaxx** [comment] 2023-01-21 15:47
Can confirm.
I think the problem is with `plugin/server/utils/translatable-fields.js#getTranslateFields` which down the line leads to the deepl provider never actually being called.

https://github.com/Fekide/strapi-plugin-translate/blob/a1b5f12a78d4d04b8426019aed3ba62b23214b8a/plugin/server/utils/translatable-fields.js#L46

seems to always eval to false @sargreal

**Comment by layaxx** [comment] 2023-01-21 16:17
@JonasGruenwald @anatolykopyl 
Can you confirm that "Configure automated translation for this field" in the strapi content-type builder > relevant collection > relevant field > edit > advanced settings is set to translate?

**Comment by anatolykopyl** [comment] 2023-01-21 20:50
@layaxx no, I don't even have this field, even though as you can see in the sidebar the translate plugin is present.
<img width="1251" alt="Screenshot 2023-01-21 at 23 47 30" src="https://user-images.githubusercontent.com/33553182/213886636-1ccbbcb3-71c6-4bd3-999a-b37de04922e8.png">

**Comment by anatolykopyl** [comment] 2023-01-21 21:00
@layaxx no, the field was empty by default. After setting it to `translate` the plugin works as expected.
Thank you very much!

**Comment by JonasGruenwald** [comment] 2023-01-22 01:43
I think this was the problem for me as well, I feel like the need to change this option for every single field for translation to work isn't communicated very clearly in the docs but that might just be me.

I'm now getting
```
 error: Translating entity failed: targetLang='en' is deprecated, please use 'en-GB' or 'en-US' instead.
```
but I suppose that's an unrelated issue.

Thank you for the help @layaxx 👍

**Comment by layaxx** [comment] 2023-01-22 10:09
I think this value is set by default now when creating new collections, but was not in a previous version. 

The deprecation was mentioned in https://github.com/Fekide/strapi-plugin-translate/issues/62 and is fixed in version 1.1.0-next.1

**Comment by sargreal** [comment] 2023-01-22 10:19
Yes, the pluginOption is set everytime a content-type is created or updated. As you probably did not do that after installation of the plugin, this did not happen.

@layaxx That is definitely a confusing thing. How do you think this should be solved? I have 3 ideas:
- Mention in the docs that content types need to be updated or the pluginOption has to be created -> Might be confusing and requires additional work
- Have translate as default when the pluginOption is not set -> Might not be intended, but customization is probably not always required?
- Generate this option on first plugin start -> Can only be done in dev mode and will probably be too invasive?

**Comment by layaxx** [comment] 2023-01-22 14:38
I think translate by default would be the most intuitive way?

**Closed** 2023-01-24 15:03 UTC
Labels: bug
