### ISSUE TITLE
Incorrect link formatting in markdown translations

### ISSUE THREAD

**Issue by adriaanvanrossum** [Fekide/strapi-plugin-translate#89] opened 2023-02-03 06:17 UTC
I noticed that after translating markdown text, the links generated are not in the expected format. The links appear as follows:

```markdown
[Text link](<https://example.com>)
```

Instead of the expected format:

```markdown
[Text link](https://example.com)
```

It's getting worse when your link ends with a `)`:

```markdown
[Text link](https://example.com/?title=(title))
```

Becomes:

```markdown
[Text link](<https://example.com/?title=(title>))
```

Please let me know if additional information is needed to resolve this issue. Thank you!

I could not find an issue for that, sorry if it's redundant or already discussed.

**Comment by layaxx** [comment] 2023-02-03 14:19
Hey, so the `[Text link](https://example.com)` -> `[Text link](<https://example.com>)` thing is due to `showdown`, the markdown -> html -> markdown converter we use. 
Cannot really figure out your second example though. The formatService does correctly do `[Text link](https://example.com/?title=(title))` -> `[Text link](<https://example.com/?title=(title)>)`

**Comment by layaxx** [comment] 2023-02-05 17:11
@adriaanvanrossum 
Just did some more research/testing. Your first example is considered expected behaviour by the parser <https://github.com/showdownjs/showdown/issues/681#issuecomment-484304316> 
I agree that this is not perfect, but it works and therefore I don't think switching parser would be worth it.

Can you give more information about the example where the link actually breaks for you?
Because for me `This is a [link](https://example.com/?title=(title)) inside some text.` is correctly translated to `Dies ist ein [Link](<https://example.com/?title=(title)>) innerhalb eines Textes.`

I am not sure what information exactly I need, but I would be interested in at least your plugin config (without your keys of course), what versions you are using (strapi/plugins/etc.), what component field you are translating (richtext?).
Best case scenario of course would be a minimal reproduction setup like in <https://github.com/Fekide/strapi-plugin-translate/issues/78> :)

**Comment by layaxx** [comment] 2023-03-01 00:29
I'm going to close this issue because as previously stated I cannot reproduce this in a way that breaks anything. Feel free to reopen if you disagree and want to provide more information @adriaanvanrossum

**Closed by layaxx** 2023-03-01 00:29 UTC
